apiVersion: v1
data:
  mapRoles: |
  - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::145129224481:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-PA198CKANAWS
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::145129224481:role/UdacityFlaskDeployCBKubectlRole
      username: build

kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-27T08:19:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1511"
  uid: 20c4c05c-6a12-4652-b103-d366aa4d8df0
